# Generated by Django 3.1.1 on 2022-09-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='Firmness',
            new_name='firmness',
        ),
    ]
